#!/bin/sh
if [ "$1" ]
then
   git reset --hard $1
else
   git reset --hard c376ae434e79dce6363aa2f7b34bbe316a9a8416
fi
git push --force
git reset --hard HEAD@{1}
git push

# TODO: I should really do something about the squid attacking the cat.